// Generated by CoffeeScript 1.8.0
var split;

split = require('./split');

module.exports = function(query, stores) {
  var graph, item, key, queries, result, _, _fn, _ref;
  queries = {};
  query = split(query, Object.keys(stores));
  _ref = query.known;
  for (key in _ref) {
    graph = _ref[key];
    if (queries[graph.__query] == null) {
      queries[graph.__query] = {
        __query: graph.__query,
        keys: [],
        queries: {}
      };
    }
    queries[graph.__query].keys.push(key);
    queries[graph.__query].queries[key] = graph;
  }
  result = [];
  _fn = function(item) {
    item.query = function(cb) {
      return stores[item.__query](item.queries, cb);
    };
    return result.push(item);
  };
  for (_ in queries) {
    item = queries[_];
    _fn(item);
  }
  if (Object.keys(query.unknown).length === 0) {
    return result;
  }
  if (stores.__dynamic == null) {
    return cb(new Error('Unknown queries'));
  }
  result.push({
    __query: '__dynamic',
    keys: Object.keys(query.unknown),
    query: function(cb) {
      return stores.__dynamic(query.unknown, cb);
    },
    queries: query.unknown
  });
  return result;
};
