// Generated by CoffeeScript 1.8.0
module.exports = function(query) {
  if (Object.keys(query).length === 0) {
    return '-- no query --';
  }
  return 'query\n' + Object.keys(query).map(function(prop) {
    return "  " + prop + " from " + query[prop].__query;
  }).join('\n');
};
