// Generated by CoffeeScript 1.8.0
var async, build, extend;

build = require('./build');

async = require('odo-async');

extend = require('extend');

module.exports = function(query, stores, callback) {
  var errors, q, state, tasks, _fn, _i, _len;
  query = build(query, stores);
  errors = [];
  tasks = [];
  state = {};
  _fn = function(q) {
    return tasks.push(function(cb) {
      return q.query(function(err, results) {
        if (err != null) {
          errors.push(err);
        } else {
          extend(state, results);
        }
        return cb();
      });
    });
  };
  for (_i = 0, _len = query.length; _i < _len; _i++) {
    q = query[_i];
    _fn(q);
  }
  return async.parallel(tasks, function() {
    if (errors.length !== 0) {
      return callback(errors, state);
    }
    return callback(null, state);
  });
};
