// Generated by CoffeeScript 1.8.0
var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

module.exports = function(query, names) {
  var key, known, unknown, value, _ref;
  known = {};
  unknown = {};
  for (key in query) {
    value = query[key];
    if (_ref = value.__query, __indexOf.call(names, _ref) >= 0) {
      known[key] = value;
    } else {
      unknown[key] = value;
    }
  }
  return {
    known: known,
    unknown: unknown
  };
};
