// Generated by CoffeeScript 1.8.0
var executequery, fillgraph, fillprop, jsonfilter, subqueries;

jsonfilter = require('./json-filter');

subqueries = {};

fillprop = function(data, graph) {
  var def;
  if (graph instanceof Array) {
    if (!(data instanceof Array)) {
      throw new Error('Expecting array', {
        data: data
      });
    }
    if (graph[0].__odoql != null) {
      def = graph[0].__odoql;
      return subqueries[def.name](data, graph);
    } else {
      return data.map(function(t) {
        return fillgraph(t, graph[0]);
      });
    }
  } else if (graph.__odoql != null) {
    def = graph.__odoql;
    return subqueries[def.name](graph, data);
  } else {
    return fillgraph(data, graph);
  }
};

fillgraph = function(data, graph) {
  var key, result, shape;
  if ((data == null) || data === null) {
    return null;
  }
  if (typeof graph !== 'object') {
    return data;
  }
  result = {};
  for (key in graph) {
    shape = graph[key];
    if (data[key] == null) {
      continue;
    }
    result[key] = fillprop(data[key], shape);
  }
  return result;
};

executequery = function(data, graph) {
  var results;
  if (graph instanceof Array) {
    graph = graph[0];
    results = jsonfilter(data, graph.__odoql.filter);
    results = results.map(function(result) {
      return fillgraph(result, graph);
    });
    return results;
  }
  results = jsonfilter(data, graph.__odoql.filter);
  results = results.map(function(result) {
    return fillgraph(result, graph);
  });
  if (results.length === 0) {
    return null;
  }
  if (results.length !== 1) {
    throw new Error('One needed, many found');
  }
  return results[0];
};

subqueries['json-filter'] = executequery;

module.exports = {
  subqueries: subqueries,
  query: executequery,
  filter: jsonfilter
};
