// Generated by CoffeeScript 1.8.0
module.exports = function(max, idle) {
  var next, result, start, _queued, _running;
  _running = {};
  _queued = {};
  start = function(key, task) {
    _running[key] = task(function() {
      delete _running[key];
      next();
      if ((idle != null) && Object.keys(_running).length === 0) {
        return idle();
      }
    });
    return next();
  };
  next = function() {
    var key, task;
    if (Object.keys(_queued).length === 0) {
      return;
    }
    if (Object.keys(_running).length >= max) {
      return;
    }
    key = Object.keys(_queued)[0];
    task = _queued[key];
    delete _queued[key];
    return start(key, task);
  };
  return result = {
    cancel: function(key) {
      if (_running[key] != null) {
        _running[key]();
        delete _running[key];
      }
      if (_queued[key] != null) {
        return delete _queued[key];
      }
    },
    exec: function(key, task) {
      result.cancel(key);
      _queued[key] = task;
      return next();
    }
  };
};
