// Generated by CoffeeScript 1.8.0
var relay;

relay = require('./relay');

module.exports = function(component, spec) {
  if (spec.query == null) {
    return component.query = function() {
      return {};
    };
  }
  component.query = function(params) {
    return spec.query.call(component, params);
  };
  return component.relay = function(el, store) {
    return relay(el, component, store);
  };
};
