// Generated by CoffeeScript 1.9.1
module.exports = {
  csv: {
    params: {
      csv: true
    }
  },
  fs: {
    params: {
      file: true
    }
  },
  http: {
    params: {
      http: true
    }
  },
  time: {
    unary: {
      asTime: true
    },
    params: {
      formatTime: true,
      deltaTime: true
    }
  }
};
