// Generated by CoffeeScript 1.8.0
var extend;

extend = require('extend');

module.exports = {
  object: function(query, params, graph) {
    return extend({}, graph, {
      __odoql: {
        query: query,
        type: 'object',
        params: params
      }
    });
  },
  array: function(query, params, graph) {
    return extend({}, graph, {
      __odoql: {
        query: query,
        type: 'array',
        params: params
      }
    });
  },
  merge: function(queries) {
    var query, result, _i, _len, _results;
    result = {};
    _results = [];
    for (_i = 0, _len = queries.length; _i < _len; _i++) {
      query = queries[_i];
      _results.push(result = extend(true, result, query));
    }
    return _results;
  },
  exec: function(queries, stores) {
    var graph, key, query, state, store;
    state = {};
    for (key in queries) {
      graph = queries[key];
      query = graph.__odoql;
      store = stores[query.query];
      state[key] = store(query, graph);
    }
    return state;
  }
};
