// Generated by CoffeeScript 1.8.0
var jsonquery;

jsonquery = require('./query');

module.exports = function(json) {
  return function(query, cb) {
    var e, key, result, value;
    try {
      result = {};
      for (key in query) {
        value = query[key];
        result[key] = jsonquery(json, value, {
          filter: jsonquery
        });
      }
      cb(null, result);
    } catch (_error) {
      e = _error;
      cb(e);
    }
    return function() {};
  };
};
