// Generated by CoffeeScript 1.9.2
var exe, ql, query;

ql = require('odoql');

ql = ql.use('csv').use('time').use('fs');

query = ql('./example2.csv').file().csv({
  header: true,
  skipEmptyLines: true
}).remove({
  __parsed_extra: true
}).rename({
  time: 'DateTime',
  location: 'Location',
  wd: 'WindDir',
  wsp: 'WSpd10m',
  gst: 'Gust10m'
}).filter(ql.eq('Location 1', ql.ref('location'))).query();

console.log(JSON.stringify(query, null, 2));

exe = require('odoql-exe');

exe = exe().use(require('odoql-csv')).use(require('odoql-fs')).use(require('odoql-time'));

exe.build(query)(function(err, results) {
  return console.log(results);
});
