// Generated by CoffeeScript 1.9.1
var cache, dynamic, exe, ql, queries;

ql = require('odoql');

ql = ql.use('store');

queries = {
  query1: ql([1, 2, 3, 4]).count().query(),
  query2: ql.store('dataset')
};

console.log(JSON.stringify(queries, null, 2));

dynamic = require('odoql-exe/dynamic');

exe = require('odoql-exe');

exe = exe().use(dynamic(function(keys, queries, cb) {
  return cb(null, queries);
}));

cache = require('odoql-exe/cache');

cache = cache(exe);

cache.on('result', function(result) {
  return console.log(result);
});

cache.run(queries);
