// Generated by CoffeeScript 1.9.1
var indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

module.exports = function(exe, params) {
  var getdata, getparams;
  getparams = exe.build(params.__params);
  getdata = exe.build(params.__source);
  return function(cb) {
    return getparams(function(err, params) {
      return getdata(function(err, data) {
        return cb(null, data.filter(function(d) {
          var key, ref, test;
          for (key in params) {
            test = params[key];
            if (d[key] === void 0) {
              return false;
            }
            if (test instanceof Array) {
              if (ref = d[key], indexOf.call(test, ref) < 0) {
                return false;
              }
            } else {
              if (d[key] !== test) {
                return false;
              }
            }
          }
          return true;
        }));
      });
    });
  };
};
