// Generated by CoffeeScript 1.9.1
module.exports = function(exe, params) {
  var getdata, getparams;
  getparams = exe.build(params.__params);
  getdata = exe.build(params.__source);
  return function(cb) {
    return getparams(function(err, params) {
      return getdata(function(err, data) {
        if (typeof data !== 'string') {
          throw new Error('Expecting string for findandreplace');
        }
        return cb(null, data.replace(new RegExp(params.find, params.flags), params.replace));
      });
    });
  };
};
