// Generated by CoffeeScript 1.9.1
module.exports = function(exe, params) {
  var getdata;
  getdata = exe.build(params.__source);
  return function(cb) {
    return getdata(function(err, data) {
      if (!(data instanceof Array)) {
        throw new Error('Not an array');
      }
      if (data.length !== 1) {
        throw new Error('No single item');
      }
      return cb(null, data.pop());
    });
  };
};
