// Generated by CoffeeScript 1.9.1
module.exports = function(exe, params) {
  var getdata, getparams;
  getparams = exe.build(params.__params);
  getdata = exe.build(params.__source);
  return function(cb) {
    return getparams(function(err, params) {
      return getdata(function(err, data) {
        var plu;
        plu = function(d) {
          return d[params];
        };
        if (err != null) {
          return cb(err);
        }
        if (data instanceof Array) {
          return cb(null, data.map(plu));
        } else {
          return cb(null, plu(data));
        }
      });
    });
  };
};
