// Generated by CoffeeScript 1.9.1
module.exports = function(exe, params) {
  var getdata, getparams;
  getparams = exe.build(params.__params);
  getdata = exe.build(params.__source);
  return function(cb) {
    return getparams(function(err, params) {
      return getdata(function(err, data) {
        var sha;
        sha = function(d) {
          var _, res, target;
          res = {};
          for (target in params) {
            _ = params[target];
            res[target] = d[target];
          }
          return res;
        };
        if (err != null) {
          return cb(err);
        }
        if (data instanceof Array) {
          return cb(null, data.map(sha));
        } else {
          return cb(null, sha(data));
        }
      });
    });
  };
};
