// Generated by CoffeeScript 1.9.1
module.exports = function(exe, params) {
  var getdata, getparams;
  getparams = exe.build(params.__params);
  getdata = exe.build(params.__source);
  return function(cb) {
    return getparams(function(err, params) {
      return getdata(function(err, data) {
        var trans;
        trans = function(d) {
          var source, target, value;
          for (target in params) {
            source = params[target];
            value = d[source];
            delete d[source];
            d[target] = value;
          }
          return d;
        };
        if (err != null) {
          return cb(err);
        }
        if (data instanceof Array) {
          return cb(null, data.map(trans));
        } else {
          return cb(null, trans(data));
        }
      });
    });
  };
};
