// Generated by CoffeeScript 1.9.1
module.exports = {
  trinary: {
    "if": function(exe, params) {
      var getleft, getparams, getright;
      getparams = exe.build(params.__p);
      getleft = exe.build(params.__l);
      getright = exe.build(params.__r);
      return function(cb) {
        return getparams(function(err, params) {
          if (err != null) {
            return cb(err);
          }
          if (params) {
            return getleft(function(err, left) {
              if (err != null) {
                return cb(err);
              }
              return cb(null, left);
            });
          } else {
            return getright(function(err, right) {
              if (err != null) {
                return cb(err);
              }
              return cb(null, right);
            });
          }
        });
      };
    },
    unless: function(exe, params) {
      var getleft, getparams, getright;
      getparams = exe.build(params.__p);
      getleft = exe.build(params.__l);
      getright = exe.build(params.__r);
      return function(cb) {
        return getparams(function(err, params) {
          if (err != null) {
            return cb(err);
          }
          if (!params) {
            return getleft(function(err, left) {
              if (err != null) {
                return cb(err);
              }
              return cb(null, left);
            });
          } else {
            return getright(function(err, right) {
              if (err != null) {
                return cb(err);
              }
              return cb(null, right);
            });
          }
        });
      };
    }
  }
};
