// Generated by CoffeeScript 1.9.1
var helpers;

helpers = require('odoql-utils/helpers');

module.exports = {
  params: {
    findandreplace: function(exe, params) {
      return helpers.params(exe, params, function(params, source) {
        if (typeof source !== 'string') {
          throw new Error('Expecting string for findandreplace');
        }
        return source.replace(new RegExp(params.find, params.flags), params.replace);
      });
    }
  },
  unary: {
    uppercase: function(exe, params) {
      return helpers.unary(exe, params, function(source) {
        return source.toUpperCase();
      });
    },
    lowercase: function(exe, params) {
      return helpers.unary(exe, params, function(source) {
        return source.toLowerCase();
      });
    },
    toString: function(exe, params) {
      return helpers.unary(exe, params, function(source) {
        return source.toString();
      });
    }
  },
  binary: {
    concat: function(exe, params) {
      return helpers.binary(exe, params, function(left, right) {
        return "" + left + right;
      });
    }
  },
  trinary: {
    substr: function(exe, params) {
      var getleft, getparams, getright;
      getparams = exe.build(params.__p);
      getleft = exe.build(params.__l);
      getright = exe.build(params.__r);
      return function(cb) {
        return getparams(function(err, params) {
          if (err != null) {
            return cb(err);
          }
          return getleft(function(err, left) {
            if (err != null) {
              return cb(err);
            }
            return getright(function(err, right) {
              if (err != null) {
                return cb(err);
              }
              return cb(null, params.substr(left, right));
            });
          });
        });
      };
    }
  }
};
